# Этот компоуз применяется для приемочного автоматического тестирования

version: '3'
services:

  app:
    image: nginx:latest
    ports:
      - "8080:80"
#    depends_on:
#      - kafka
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      # Во внутренней сети docker-compose слушаем адрес kafka:9092
      # Из внешней сети docker-compose будем слушать localhost:9094
      # Как альтерантива, можно вычислять адрес как-то так:
      # HOSTNAME_COMMAND: curl http://169.254.169.254/latest/meta-data/public-hostname
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes


#  logstash:
#    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
#    depends_on:
#      - kafka
#      - opensearch
#    ports:
#      - "5044:5044"
#      - "1111:1111"
#    environment:
#      BOOTSTRAP_SERVERS: "kafka:9092"
#    volumes:
##      - ./volumes/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./volumes/logstash/10-mp-logs.conf:/usr/share/logstash/pipeline/10-mp-logs.conf
#
#  opensearch:
#    image: opensearchproject/opensearch:latest
#    environment:
#      - discovery.type=single-node
#      - http.port=9200
#      - bootstrap.memory_lock=true
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    ports:
#      - '9200:9200'
#      - '9600:9600'
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    volumes:
#      - opensearch-data:/usr/share/opensearch/data
